export let rides:Array<object> = [
  {
    rideID: 1,
    date:"31-10-2023",
    startLocationName: "Agency Hotel",
    startLocationAdress: "Runderweg 11 1234 AB Amsterdam",
    distance:20,
    destinationName: "Jumbo Online",
    destinationAdress:"Gyroscoopweg 10 1042 AC Amsterdam",
  },  
  {
    rideID: 2,
    date:"31-10-2023",
    startLocationName: "Jumbo Online",
    startLocationAdress:"Gyroscoopweg 10 1042 AC Amsterdam",
    distance:20,
    destinationName: "Agency Hotel",
    destinationAdress: "Runderweg 11 1234 AB Amsterdam",
  },
  {
    rideID: 3,
    date:"31-10-2023",
    startLocationName: "Agency Headquaters",
    startLocationAdress:"Valkhofparkstraat 123 1122 AD Nijmegen",
    distance:117,
    destinationName: "Agency Hotel",
    destinationAdress: "Runderweg 11 1234 AB Amsterdam",
  },
  {
    rideID: 3,
    date:"31-10-2023",
    startLocationName: "Agency Hotel",
    startLocationAdress: "Runderweg 11 1234 AB Amsterdam",
    distance:117,
    destinationName: "Agency Headquaters",
    destinationAdress:"Valkhofparkstraat 123 1122 AD Nijmegen",
  },
]